[build]
builder = "nixpacks"
buildCommand = "npm install && cd server && npm install"
startCommand = "caddy run --config /app/Caddyfile & cd server && node index.js"
installCommand = "npm install -g @caddyserver/linux-arm64 && npm install"

[build.environment]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "caddy run --config /app/Caddyfile & cd server && node index.js"
port = 80

[[build.extra_packages]]
name = "caddy"