[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"
startCommand = "cd server && node index.js"

[build.environment]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "cd server && node index.js"
port = 3000

[build.extra_packages]
# No need for Caddy as Railway handles SSL termination