[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"
startCommand = "cd server && PORT=8080 node index.js"

[build.environment]
NODE_ENV = "production"
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"
PORT = "8080"

[deploy]
startCommand = "cd server && PORT=8080 node index.js"
port = 8080

[build.extra_packages]
# No extra packages needed